name: Train
on:
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Build Docker image
        run: docker build -t yourdockerhubusername/cicd_assignment:${{ github.sha }} .
      - name: Push Docker image to registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push yourdockerhubusername/cicd_assignment:${{ github.sha }}
        if: success()
 
