name: Train
on:
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Build Docker image
        run: docker build -t nithinpoovanna/cicdassignment:v3 .
      - name: Push Docker image to registry
        run: |
          echo "${{ secret.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push nithinpoovanna/cicdassignment:v3
